name: Test and Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Artifacts version'
        required: true
        default: '1.0.0'

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x # Used in Nezaboodka.Nevod.Example.csproj
      - name: Build
        run: dotnet build Source/Nezaboodka.Nevod.sln -c Release

  test-nevod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Test
        run: |
          dotnet test Source/Engine.Tests/Nezaboodka.Nevod.Engine.Tests.csproj -c Release --verbosity normal --test-adapter-path:. \
            --logger:"junit;LogFilePath=..\..\Build\TestResults\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: Build/TestResults/*-test-result.xml

  test-negrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Test
        run: |
          dotnet test Source/Negrep.Tests/Nezaboodka.Nevod.Negrep.Tests.csproj -c Release --verbosity normal --test-adapter-path:. \
            --logger:"junit;LogFilePath=..\..\Build\TestResults\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: Build/TestResults/*-test-result.xml

  test-text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Test
        run: dotnet test Source/Text.Tests/Nezaboodka.Text.Tests.csproj -c Release --verbosity normal

  build-negrep-artifacts:
    runs-on: ubuntu-latest
    needs:
      - build-all
      - test-nevod
      - test-negrep
      - test-text
    strategy:
      matrix:
        target-os: [ "linux_x64", "windows_x64", "windows_x86", "osx_x64" ]
    env:
      NV_DOCK_TAG: github
    steps:
      - name: Set NG_VERSION variable from tag
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: echo "NG_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Set NG_VERSION variable to 0.0.1 for test builds
        if: ${{ !startsWith(github.ref, 'refs/tags') && (github.event_name != 'workflow_dispatch') }}
        run: echo "NG_VERSION=0.0.1" >> $GITHUB_ENV
      - name: Set NG_VERSION variable for manual trigger
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "NG_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - run: chmod +x ./Deployment/publish.sh
      - run: ./Deployment/publish.sh ${{ matrix.target-os }}
        shell: sh
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target-os }}
          path: Publish/

  test-negrep-linux-zip-package:
    runs-on: ubuntu-latest
    needs: build-negrep-artifacts
    strategy:
      matrix:
        target-os: [ "centos_x64", "ubuntu_x64" ]
    env:
      NV_DOCK_TAG: github
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: linux_x64
          path: Publish
      - run: chmod +x ./Deployment/smoke_test.sh
      - run: ./Deployment/smoke_test.sh ${{ matrix.target-os }}
        shell: sh

  test-negrep-osx-zip-package:
    runs-on: macos-latest
    needs: build-negrep-artifacts
    env:
      NV_DOCK_TAG: github
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: osx_x64
          path: Publish
      - run: chmod +x ./Deployment/smoke_test_osx.sh
      - run: ./Deployment/smoke_test_osx.sh
        shell: sh

  test-negrep-deb-package:
    runs-on: ubuntu-latest
    needs: build-negrep-artifacts
    env:
      NV_DOCK_TAG: github
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: linux_x64
          path: Publish
      - run: chmod +x ./Deployment/test_packages.sh
      - run: ./Deployment/test_packages.sh
        shell: sh

  test-windows-zip-package:
    runs-on: windows-latest
    needs: build-negrep-artifacts
    strategy:
      matrix:
        windows-version: [ "windows_x86", "windows_x64" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.windows-version }}
          path: Publish
      - run: ./Deployment/smoke_test_windows.ps1 ${{ matrix.windows-version }}
        shell: pwsh

  publish-nevod-nuget-package:
    if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    needs:
      - test-negrep-linux-zip-package
      - test-negrep-osx-zip-package
      - test-negrep-deb-package
      - test-windows-zip-package
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build Source/Engine/Nezaboodka.Nevod.Engine.csproj --configuration Release /p:Version=${VERSION}
      - name: Pack
        run: dotnet pack Source/Engine/Nezaboodka.Nevod.Engine.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push
        run: dotnet nuget push Nezaboodka.Nevod.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NEVOD_NUGET_TOKEN}
        env:
          NEVOD_NUGET_TOKEN: ${{ secrets.NEVOD_NUGET_TOKEN }}

  publish-text-nuget-package:
    if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    needs:
      - test-negrep-linux-zip-package
      - test-negrep-osx-zip-package
      - test-negrep-deb-package
      - test-windows-zip-package
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build Source/Text/Nezaboodka.Text.csproj --configuration Release /p:Version=${VERSION}
      - name: Pack
        run: dotnet pack Source/Text/Nezaboodka.Text.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push
        run: dotnet nuget push Nezaboodka.Text.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NEVOD_NUGET_TOKEN}
        env:
          NEVOD_NUGET_TOKEN: ${{ secrets.NEVOD_NUGET_TOKEN }}

  create-github-release:
    if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    needs:
      - publish-text-nuget-package
      - publish-nevod-nuget-package
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: release-artifacts
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release-artifacts/**/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBody: true
